///////////////////////////////////////////////////////////////////////////////////////////////////
// This module generates PID feedback signals for the robot for controling the left and right
// motor speed.
///////////////////////////////////////////////////////////////////////////////////////////////////
module PID(

    input wire clk, rst_n, moving, hdng_vld, 
    input wire signed [11:0]dsrd_hdng, actl_hdng,
    input wire [10:0]frwrd_spd,
    output logic at_hdng,
    output logic signed [11:0]lft_spd, rght_spd


);

// Signal generated by and used in P_term
wire signed[11:0]error;
wire [13:0]P_term;
logic signed [9:0]err_sat;
localparam signed [3:0]P_COEFF = 4'h3;

// Signals used in and generated by I_term
wire signed [11:0]I_term;
wire ov;
wire signed [15:0]integrator_sum_mux, moving_mux, nxt_integrator;
reg signed [15:0]integrator;

// Signals used in and generated by D_term
localparam signed D_COEFF = 5'h0E;
reg signed [9:0]err_sat_dt1;
reg signed [9:0]err_sat_dt2;
logic signed [10:0]D_diff;
logic signed [7:0]D_diff_sat;
wire signed [12:0]D_term;

// Pipline Reg for err_sat to meet time delay for multipliers and adders in the PID calculations
logic signed [9:0]err_sat_D;

///////////////////////////////////////////////////////////////////////////////////////////////////
// The robot is at the deired heading if the saturated error ( saturated difference from acutal and
// desired) is less than |30|.
///////////////////////////////////////////////////////////////////////////////////////////////////

    assign at_hdng = (err_sat_D < 10'sd30 & $signed(err_sat_D) > $signed(-10'sd30));

///////////////////////////////////////////////////////////////////////////////////////////////////
// Generate the proportional control signal for the PID controller and Saturated error signal.
///////////////////////////////////////////////////////////////////////////////////////////////////

always_ff @(posedge clk)
    err_sat <= err_sat_D;

// Generate error signal
assign error = actl_hdng - dsrd_hdng;

// Saturate error if outside of bounds, pass original if in bounds
assign err_sat_D = (error[11] && ~&error[10:9]) ? 10'h200 :
    (!error[11] && |error[10:9]) ? 10'h1FF : error[9:0];

assign P_term = err_sat * P_COEFF;

///////////////////////////////////////////////////////////////////////////////////////////////////
// Generate the Integral component of the PID controller. Creates a rolling sum of the past values
// of error_sat. Accumulation is paused when overflow would occur. If the heading is invalid,
// don't don't accumulate. Synch Reset accumulation if not moving.
///////////////////////////////////////////////////////////////////////////////////////////////////

// Sign extend and add err_sat with roling sum integrator
assign integrator_sum_mux = {{6{err_sat[9]}}, err_sat[9:0]} + integrator;


// The rolling sum has overflown if both inputs are positive and output is negative, or both 
// inputs are negative and output is positive.
assign ov = ((integrator[15] && err_sat[9] && !integrator_sum_mux[15]) || 
            (!integrator[15] && !err_sat[9] && integrator_sum_mux[15]));

// Select next value of I_term
assign moving_mux = (hdng_vld && !ov) ? integrator_sum_mux : integrator;
assign nxt_integrator = (moving) ? moving_mux : 16'h0000;

// Right shfit integrator and contract to fewer bits to make I_term.
assign I_term = integrator[15:4];

// Register that stores the current I_term
always_ff @(posedge clk, negedge rst_n) begin
    if (!rst_n) 
        integrator <= 16'h0000;
    else
    integrator <= nxt_integrator;

end

///////////////////////////////////////////////////////////////////////////////////////////////////
// Generate the Derivative term for the PID controller. The D_term is based on the difference of
// the current and error_sat from two samples previous.
///////////////////////////////////////////////////////////////////////////////////////////////////

// Subtract current and previous value of err_sat to create derivated D_diff thenSaturate D_diff
always_comb begin
    D_diff = err_sat - err_sat_dt2;

    // Divide by 8. If the difference overflowed, or cannot be reprsented in 8 bits saturate it.
    if(D_diff[10]  && ~&D_diff[9:7]) begin

        // negative saturation
        D_diff_sat = 8'h80;

    end else if (~D_diff[10] && |D_diff[9:7]) begin

        // postivie saturation
        D_diff_sat = 8'h7F;

    end else begin 

        D_diff_sat = D_diff[7:0];

    end
end

// Scale by the D coefficient
assign D_term = D_diff_sat * D_COEFF;


// This flop stores the value of err_sat from the previous clock cycle
always_ff @(posedge clk, negedge rst_n) begin
    
    if(!rst_n) begin
        err_sat_dt1 <= 10'h000;
    end else if(hdng_vld) begin
        err_sat_dt1 <= err_sat;
    end

end

// This flop stores the value of err_sat from two clock cycles previous (stores val from flop above)
always_ff @(posedge clk, negedge rst_n) begin
    if(!rst_n) begin
        err_sat_dt2 <= 10'h000;
    end else if (hdng_vld) begin
        err_sat_dt2 <= err_sat_dt1;
    end
end



///////////////////////////////////////////////////////////////////////////////////////////////////
// Add all the outputs of the feedback blocks P, I and D, and divide by 8.
///////////////////////////////////////////////////////////////////////////////////////////////////

logic signed [14:0]PID_sum;
logic signed [11:0]PID_sum_div8;
logic signed [11:0]PID_sum_div8_pipe;

always_ff @(posedge clk) begin

    PID_sum_div8_pipe <= PID_sum_div8;

end

always_comb begin

    PID_sum = $signed(P_term) + $signed(I_term) + $signed(D_term);
    PID_sum_div8 = {PID_sum[14:3]};

end

///////////////////////////////////////////////////////////////////////////////////////////////////
// Generate final speed control values for the left motor. lft_spd is 0 if the robot is not moving.
// Otherwise it is the forward of forward speed with the scaled sum of the feeback blocks.
///////////////////////////////////////////////////////////////////////////////////////////////////

logic signed [11:0]lft_sum;

always_comb begin

    lft_sum = PID_sum_div8_pipe + {1'b0, frwrd_spd};
    // Don't power the motors if the robot isn't moving
    lft_spd = (moving) ? lft_sum : 12'h000;

end

///////////////////////////////////////////////////////////////////////////////////////////////////
// Generate final speed control values for the left motor. rght_spd is 0 if the robot is not 
//moving. Otherwise it is the difference of forward speed and the scaled sum of the feeback blocks.
///////////////////////////////////////////////////////////////////////////////////////////////////

logic signed [11:0]rght_sum;

always_comb begin

    rght_sum = {1'b0, frwrd_spd} - PID_sum_div8_pipe;

    // Don't power the motors if the robot isn't moving
    rght_spd = (moving) ? rght_sum : 12'h000;

end

endmodule